### ISSUE TITLE
platform_tag is wrong on macOS for Homebrew Python

### ISSUE THREAD

**Issue by mkoeppe** [FFY00/meson-python#91] opened 2022-07-03 19:33 UTC
meson-python 0.6.0 generates a wheel the platform tag `macosx_12_x86_64`, which cannot be installed by pip.

Ref: https://trac.sagemath.org/ticket/34081#comment:15

Why not use https://github.com/pypa/packaging/blob/main/packaging/tags.py?

**Comment by rgommers** [comment] 2022-07-04 14:25
I double checked on Linux, and (as expected) it's fine there: `scipy-1.10.0.dev0-cp310-cp310-linux_x86_64.whl`.

**Comment by rgommers** [comment] 2022-07-05 16:24
Hmm, after looking into this some more, this is indeed very incomplete:
- `mesonpy/_tags.py` is writting from scratch and only supports Linux, and Windows partially (plus a stable ABI tag)
- `_select_abi_tag` in `__init__.py` does some checks, but if something doesn't match the linux/windows/stable tags, it happily returns an incorrect tag

> Why not use https://github.com/pypa/packaging/blob/main/packaging/tags.py?

I agree, there's no need to reinvent this wheel. That file is compatibly-licensed, so can be reused.

**Comment by FFY00** [comment] 2022-07-05 20:14
The big difference from our code to pypa/packaging is that we derive our tags directly from the extension modules, while pypa/packaging tries to list all compatible tags for the current interpreter.

While I still think our code is valuable, but we should definitely make use of pypa/packaging too.

**Comment by rgommers** [comment] 2022-07-05 20:39
> The big difference from our code to pypa/packaging is that we derive our tags directly from the extension modules

Does that help much / is that going to be robust? On Linux I see a useful extension, like `*.cpython-310-x86_64-linux-gnu.so`. On macOS that doesn't seem to be the case though, the extensions are simply `.cpython-39-darwin.so`. No architecture included, nor the macOS version (typically given by `MACOSX_DEPLOYMENT_TARGET`).

**Comment by mkoeppe** [comment] 2022-07-05 20:51
https://github.com/pypa/wheel/blob/main/src/wheel/bdist_wheel.py and https://github.com/pypa/wheel/blob/main/src/wheel/macosx_libfile.py also have relevant code.

**Comment by FFY00** [comment] 2022-07-06 17:47
> Does that help much / is that going to be robust?

Yep, because the modules can be built with the stable ABI for eg. In Linux it seems the extension tag are a direct mapping but this is not the case for macOS.

Unfortunately, the spec says the correct platform-specific tag is defined by `distutils.util.get_platform`, which we have to recreate now in the downstream because `distutils` is deprecated. We can use `wheel.macosx_libfile.calculate_macosx_platform_tag`.

**Comment by rgommers** [comment] 2022-07-06 17:57
Makes sense. I actually wouldn't know how we'd go from "detect this uses the stable ABI" to extension name. Does `sysconfig` check for `Py_LIMITED_API` when retrieving the extension or some such thing?

**Comment by eli-schwartz** [comment] 2022-07-07 01:50
I suppose that is something that could be added to Meson if people want it. Personally, I haven't really seen the limited API used in projects much...

The implementation would probably look something like `limited: true` as a kwarg to extension module which automatically defines Py_LIMITED_API and sets the soname? Incidentally, Meson uses EXT_SUFFIX. :)

**Comment by FFY00** [comment] 2022-07-07 16:47
Hi Eli, that sounds like a good proposal. I would probably call the option something like `limited_abi` to be more explicit, though. Additionally, the argument should be the version to set in `Py_LIMITED_API`.

See https://docs.python.org/3/c-api/stable.html#stable-application-binary-interface

> Meson uses EXT_SUFFIX

Which itself is based on `SOABI` :stuck_out_tongue:. The correct way to build the name in this satiation would be `'.'.join(extension_name, f'abi{limited_abi_vbersion}', sysconfig.get_config_var('SHLIB_SUFFIX'))'`

**Comment by FFY00** [comment] 2022-07-20 18:28
Opened https://github.com/pypa/packaging/issues/578, so I'll close this. @rgommers once you manage to verify if the bug you mentioned still exists, please open a new PR if it does. Thanks!

@mkoeppe do let me know if you have further feedback or you think I missed anything :blush:

**Comment by rgommers** [comment] 2022-07-22 07:57
> > I see a second issue, the ABI tag is incorrect:
> 
> I think that was just #95, can you check against `main`?

Correct, that was gh-95, unrelated to this issue.

> Opened [pypa/packaging#578](https://github.com/pypa/packaging/issues/578), so I'll close this.

I determined that the problem is Homebrew-specific, so I'll update the title of this issue. It's not actually fixed until a new `packaging` release with the fix comes out, so other people are likely to run into this. Hence I'll reopen this and add a "dependency-bug" label. Once the fix is out, we should bump the minimum `packaging` version in this repo so it includes that fix.

**Comment by mkoeppe** [comment] 2022-07-22 17:50
> It's not actually fixed until a new `packaging` release with the fix comes out

More precisely, until a new `pip` release comes out that vendors a fixed `packaging` (https://github.com/pypa/pip/tree/main/src/pip/_vendor/packaging)

**Comment by rgommers** [comment] 2022-07-22 17:59
Thanks for the correction. Or, alternatively, if Homebrew fixes what they're doing here - or we add a workaround for it in this package. `pip` is a pain, because even if it is fixed in a new release, people tend to use older pip versions for a long time.

**Comment by mkoeppe** [comment] 2022-07-22 19:07
+1 on preparing a workaround.

**Comment by rgommers** [comment] 2022-07-26 11:03
This was fixed in gh-111, which is in `0.8.0`.

**Closed by rgommers** 2022-07-26 11:03 UTC
Labels: dependency-bug

**Comment by mkoeppe** [comment] 2022-07-26 19:04
Thanks a lot, I confirm that it fixes the problem.

**Comment by mkoeppe** [comment] 2022-08-01 01:18
I now have a similar problem on Linux 32-bit userspace on 64-bit, opened #123

**Comment by mkoeppe** [comment] 2022-09-30 01:36
This problem has come back with meson-python 0.9.0

https://trac.sagemath.org/ticket/34081#comment:90

**Comment by rgommers** [comment] 2022-09-30 07:41
That's not the same, let me open a new issue to discuss.
