### ISSUE TITLE
Ill-formatted METADATA results in invalid sdist

### ISSUE THREAD

**Issue by rgommers** [FFY00/meson-python#67] opened 2022-05-29 11:56 UTC
I'm not sure if this is an issue with `meson-python` or with `pip`, because PEP 517 is not clear at all whose responsibility it is to deal with runtime dependencies, and how exactly.

For SciPy we declare a runtime dependency like so in `pyproject.toml`:
```toml
[project]
dependencies = [
    "numpy>=1.18.5",
]
```

This info does end up in the wheel, in `scipy-1.9.0.dev.dist-info/METADATA` as:
```
Requires-Dist: numpy>=1.18.5
```

However, Pip seems to completely ignore that:
```
$ python -m build
$ pip install dist/scipy-1.9.0.dev0-cp310-cp310-linux_x86_64.whl 
Processing ./dist/scipy-1.9.0.dev0-cp310-cp310-linux_x86_64.whl
Installing collected packages: scipy
Successfully installed scipy-1.9.0.dev0
```

The last line of the above should have said:
```
Successfully installed numpy-1.22.4 scipy-1.9.0.dev0
```

**Comment by rgommers** [comment] 2022-05-29 13:31
Looks like a `meson-python` bug, the format should have brackets:
```
Requires-Dist: numpy (>=1.17.0)
```
@FFY00 you may know if there's a standards doc for this? Either way, the pragmatic solution seems to be to match the `bdist_wheel`/`setuptools` formatting here, that should work.

**Comment by rgommers** [comment] 2022-05-29 13:37
Argh no, tried it by manually unzipping, editing metadata, and re-zipping - it does not make a difference.

This `Requires-Dist:` is the only metadata entry in the wheel, so it's a bit of a mystery to me what is going on here.

**Comment by FFY00** [comment] 2022-05-29 14:03
I will look into it.

The missing parenthesis should not be the problem, in fact, that is correct.

See https://packaging.python.org/en/latest/specifications/core-metadata/#requires-dist-multiple-use

> A version specifier. Tools parsing the format should accept optional parentheses around this, but tools generating it should not use parentheses.

One possible thing that comes to mind is the lack of spaces before the version specifier, but I don't think that *should* be a problem.

**Comment by FFY00** [comment] 2022-05-29 14:17
I was able to reproduce this, the issue seems to be that the generated `METADATA` file is ill-formated due to newlines in the summary field, everything after it was being interpreted as the description.

Related #2

We currently don't do any validation in this field, but it is indeed supposed to be only one line.

https://packaging.python.org/en/latest/specifications/core-metadata/#summary

> A one-line summary of what the distribution does.

**Comment by rgommers** [comment] 2022-05-29 15:09
Ah, good catch, thanks. In `setup.py` we dynamically get rid of newlines it looks like, with:
```
        description=DOCLINES[0],
        long_description="\n".join(DOCLINES[2:]),
```
So here I just need to edit `pyproject.toml` to be correct from the start.

This is a confusing issue, so a check for newlines would be nice to have in `meson-python`.

**Comment by FFY00** [comment] 2022-05-29 15:52
We can also remove newlines in the backend. And `pep621` should do this validation anyway.

**Comment by rgommers** [comment] 2022-05-29 16:04
Happy with either removing in the backend or erroring out, whatever you think is better. Once you see the issue, it's very easy to fix.

**Comment by FFY00** [comment] 2022-07-07 17:00
This should be fixed with the latest `pyproject-metadata`. I opened https://github.com/FFY00/python-pyproject-metadata/issues/30 to track the `description` valudation.

**Closed by FFY00** 2022-07-07 17:00 UTC
Labels: bug
